config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  match '/home/index' => 'home#index', via: [:get, :post]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	require 'csv'
	def index
		return unless params[:file].present?
		data = []
    compare_value = Proc.new { |element| element.first == MATCHING_ID }
    csv = CSV.read(params[:file].path)
    end_range = csv.size - ONE
    csv[ZERO..end_range].each_with_index do |row, index|
      data << { row: row, rolling_percent: calculate_rolling_percent(csv, index, compare_value) }
    end
    start_and_end_index = start_and_end_indexes(data)
    @start_period = csv[start_and_end_index.first]
    @end_period = csv[start_and_end_index.last]
    @total_duration = csv[start_and_end_index.first..start_and_end_index.last].select(&compare_value).count.to_f / HOUR.to_f
	end

  private
  def calculate_rolling_percent(data, index, compare_value)
    if index >= ONE_FIFTY
      first_index = index
      second_index = index - ONE_FOURTY_NINE
      data[second_index..first_index].select(&compare_value).count.to_f / ONE_FIFTY.to_f
    end
  end

  def start_and_end_indexes(data)
  	triggered_index = ZERO
  	end_index = ZERO
  	data.each_with_index do |hash, index|
  		if hash[:rolling_percent].present? && hash[:rolling_percent] >= ROLLING_PERCENT
  			furthur_epochs = index + ONE_FIFTY
  			end_epochs = index + THREE_SEVENTY_FIVE
  			is_start = data[index..furthur_epochs].detect { |data| data[:rolling_percent] < ROLLING_PERCENT }
  			is_end = data[index..end_epochs].detect { |data| data[:rolling_percent] > ROLLING_PERCENT }
  			triggered_index = index unless is_start.present? || triggered_index > ZERO
  			unless is_end.present?
         end_index = index
         break
  			end
  		end
  	end
  	[triggered_index - ONE_FOURTY_NINE, end_index]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_analysed_data.html.erb
<table class="table table-striped table-wd">
  <thead>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Start Of Period</th>
      <td><%= DateTime.parse(@start_period.second).strftime('%Y-%m-%d %H:%M') %></td>
    </tr>
    <tr>
      <th scope="row">End Of Period</th>
      <td><%=  DateTime.parse(@end_period.last).strftime('%Y-%m-%d %H:%M')%></td>
    </tr>
    <tr>
      <th scope="row">Period Duration</th>
      <td><%= @total_duration %></td>
    </tr>
  </tbody>
</table>

app/views/home/index.html.erb
<%= form_tag home_index_path, multipart: true, class:"form-horizontal", id:"import_user_list_form" do %>
  <div class="row">
  	<div class="form-group">
	  	<div class="col-md-10">
	 			<%= file_field_tag :file, id: "csv-file", accept: ".csv", allowed_size: "5" %>
	 	 	</div>
 	 </div>
 	  <div class="form-group">
	 	 	<div class="col-md-6">
	 	 		<%= submit_tag "Import", class: "btn btn-primary", id: 'import_user_list' %>
	 		</div>
 		</div>
 	</div>
<%end%>

<%if @start_period.present?%>
	<%= render partial: 'analysed_data'%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UnoTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-expand-lg nav-color">
  <div class="container">
    <p class="navbar-brand nav-text" href="#" >Read CSV</a>
  </div>
</nav>
<div class="container">
  <!-- Content here -->


  <%= yield %>

</div>

</body>
</html>